#!/bin/bash

#echo -e 'power on\nconnect \t \nquit' | /usr/bin/bluetoothctl

date >> /home/root/btconnect.log
echo -e "connect C8:84:47:1B:0D:B8\nquit\n" | bluetoothctl > /dev/null &
exit 0

#if [[ $? -eq 0 ]]; then
#  exit 0
#else
#  exit 1
#fi


#/usr/bin/bluetoothctl << EOF
#connect C8:84:47:1B:0D:B8
#EOF
