#!/usr/bin/env python
# This script ...
#
# Timothy Crone (tjcrone@gmail.com)

# imports
import subprocess, time, argparse

# get url of the latest podcast episode
def get_stream_url(stream_name):
  if stream_name == 'thegist':
    r = requests.get('http://feeds.feedburner.com/TheGistWithMikePesca')
    for line in r.iter_lines():
      if 'enclosure' in line:
        stream_url = line.split('"')[1]
        break
  if stream_name == "majority":
    r = requests.get('http://feeds.feedburner.com/MajorityReport')
    for line in r.iter_lines():
      if 'mp3' in line:
        stream_url = line.split('"')[1]
        break
  return stream_url

# download podcast file
def download_file(stream_name, stream_url, stream_file):
  if stream_name == 'thegist':
    with open(stream_file, 'wb') as handle:
      r = requests.get(stream_url, stream=True)
      if r.ok:
        for block in r.iter_content(1024):
          handle.write(block)
  if stream_name == 'majority':
    command = "curl -s -L %s > %s" % (stream_url, stream_file)
    subprocess.call(command, shell=True)

# version function
version = '0.1dev'
def get_version():
  return ('%%(prog)s version %s' % version)

# parse arguments
parser = argparse.ArgumentParser(description='Streamer to bluetooth speakers')
parser.add_argument('-v', '--version', action='version', version=get_version())
parser.add_argument("-s", dest="stream_name", metavar="stream", type=str,
  default='wnyc', help="stream to stream (default: wnyc)")
parser.add_argument("-q", dest="quiet", action='store_true',
  default=False, help="suppress screen output")
args = parser.parse_args()

# define stream parameters based on stream_name
if args.stream_name == 'thegist':
  import requests
  stream_url = get_stream_url(args.stream_name)
  stream_eq = '-4:-4:-2:0:0:0:0:0:0:0'
if args.stream_name == 'majority':
  import requests
  stream_url = get_stream_url(args.stream_name)
  stream_eq = '-4:-4:-6:-6:-2:0:0:0:0:0'
if args.stream_name == 'majoritylive':
  stream_url = 'http://live.majority.fm:8000/live'
  stream_eq = '-4:-4:-6:-6:-2:0:0:0:0:0'
if args.stream_name == 'wnyc':
  stream_url = 'http://fm939.wnyc.org/wnycfm'
  stream_eq = '-4:-4:-6:-2:0:0:0:0:0:0'

# kill any current streams
command = "killall -q mplayer"
subprocess.call(command, shell=True)

# unblock bluetooth
command = "rfkill unblock bluetooth"
subprocess.call(command, shell=True)

# connect to speaker
bt_sink="bluez_sink.C8_84_47_1B_0D_B8"
bt_device = "C8:84:47:1B:0D:B8"
while 1:
  try:
    command = "pactl list sinks | grep Name | grep %s" % bt_sink
    bt_avail = subprocess.check_output(command, shell=True)
    break
  except:
    command = "echo -e \"connect %s\\nquit\\n\" | bluetoothctl > /dev/null" % bt_device
    subprocess.call(command, shell=True)
  time.sleep(2)

# play stream
command = "mplayer -ao pulse::%s -nolirc -prefer-ipv4 -slave -input file=/home/root/btstream/.btfifo -af equalizer=%s -noconsolecontrols %s 2>/dev/null > /dev/null &" % (bt_sink, stream_eq, stream_url)
subprocess.call(command, shell=True)
