#!/bin/bash
# Daemon to find bluetooth speakers and play WNYC.
#
# Timothy Crone
# tjcrone@gmail.com

pidfile="/var/run/mplayer.pid"
device="C8:84:47:1B:0D:B8"
sink="bluez_sink.C8_84_47_1B_0D_B8"
stream="http://fm939.wnyc.org/wnycfm"
stream="http://live.majority.fm:8000/live"

# unblock bluetooth (do this more than once?)
rfkill unblock bluetooth

# kill any running mplayer
kill -15 $(cat $pidfile) && rm $pidfile

while true; do
  dummy=`/usr/bin/pactl list sinks | grep Name | grep $sink`
  if [[ $? -eq 1 ]]; then # pulse sink is not available
    if [[ -e $pidfile ]]; then # mplayer is still running
      echo "killing mplayer and deleting pidfile"
      kill -15 $(cat $pidfile) && rm $pidfile
    fi
    #l2ping -c 1 C8:84:47:1B:0D:B8
    #echo "waiting for speaker $SECONDS"
    #echo -e "connect ${device}\nquit" | /usr/bin/bluetoothctl
    #/home/root/btconnect
  elif [[ ! -e $pidfile ]]; then
    echo "sink available"
    echo "starting mplayer"
    mplayer -ao pulse::$sink -nolirc -prefer-ipv4 -af equalizer=-12:-12:-2:2:0:0:0:0:0:0 -noconsolecontrols $stream > /dev/null &
    echo $! > /var/run/mplayer.pid
  #elif [[ -e $pidfile ]]; then
    #echo "doing nothing (mplayer running) $SECONDS"
  fi
  sleep 1
done
